import buffer = require('buffer');
import fs = require('./node_fs.d.ts');
import path = require('path');
import file_system = require('./file_system.d.ts');
import EmscriptenFS from '../generic/emscripten_fs.d.ts';
import * as FileSystem from './backends.d.ts';
import * as BFSUtils from './util.d.ts';
export declare function install(obj: any): void;
export declare function registerFileSystem(name: string, fs: file_system.FileSystemConstructor): void;
export declare function BFSRequire(module: 'fs'): typeof fs;
export declare function BFSRequire(module: 'path'): typeof path;
export declare function BFSRequire(module: 'buffer'): typeof buffer;
export declare function BFSRequire(module: 'process'): typeof process;
export declare function BFSRequire(module: 'bfs_utils'): typeof BFSUtils;
export declare function BFSRequire(module: string): any;
export declare function initialize(rootfs: file_system.FileSystem): file_system.FileSystem;
export { EmscriptenFS, FileSystem };
