#!/bin/sh
# postinst script for peergos
#
# see: dh_installdeb(1)
if [ ! -f /usr/bin/peergos ]; then
    ln -s /opt/peergos/bin/peergos /usr/bin
fi

cp /opt/peergos/lib/peergos-peergos.desktop ~/Desktop/peergos.desktop

set -e

# summary of how this script can be called:
#        * <postinst> `configure' <most-recently-configured-version>
#        * <old-postinst> `abort-upgrade' <new version>
#        * <conflictor's-postinst> `abort-remove' `in-favour' <package>
#          <new-version>
#        * <postinst> `abort-remove'
#        * <deconfigured's-postinst> `abort-deconfigure' `in-favour'
#          <failed-install-package> <version> `removing'
#          <conflicting-package> <version>
# for details, see https://www.debian.org/doc/debian-policy/ or
# the debian-policy package

case "$1" in
    configure)
xdg-desktop-menu install /opt/peergos/lib/peergos-peergos.desktop
    ;;

    abort-upgrade|abort-remove|abort-deconfigure)
    ;;

    *)
        echo "postinst called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac

exit 0
