#!/usr/bin/env python
import time
import sys
import os.path

from subprocess import Popen, call

#add geckodriver to path for FF selenium driver
os.environ["PATH"] += os.pathsep + os.path.join(os.getcwd(), 'chromedriver')

RUN_SERVER_CMD = "ant  -buildfile ../build.xml run"
# start server via ant target  in parent
p = Popen(RUN_SERVER_CMD.split(), stdout=sys.stdout)

# wait for setup 
time.sleep(2)

try:
    # run tests
    test_rc = call(['pytest', '-sv', 'tests'], stdout=sys.stdout)
    sys.exit(test_rc)
finally:
    # kill server
    p.terminate()
