name: Jar build

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK
      uses: actions/setup-java@v3
      with:
        distribution: temurin
        java-version: 17
    - name: Install graalvm
      shell: bash
      run:  cd native-build && java InstallGraalNode.java
    - name: Build with Ant
      run: ant -noinput -buildfile build.xml peergos_submodule_sync dist 
    - name: Upload jar artifact
      uses: actions/upload-artifact@v2
      with:
        name: Peergos.jar
        path: "./server/Peergos.jar"
    
