name: Jar build

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [ '17', '21', '23', '24']
    permissions:
      id-token: write
      contents: read
      attestations: write
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK ${{ matrix.Java }}
      uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: ${{ matrix.Java }}
    - name: Build with Ant
      run: ant -noinput -buildfile build.xml peergos_submodule_sync dist 
    - name: Create jar attestation
      uses: actions/attest-build-provenance@v1.0.0
      with:
        subject-path: '${{ github.workspace }}/server/Peergos.jar'

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: Peergos-java-${{ matrix.Java }}.jar
        path: "./server/Peergos.jar"
