name: Native build

on: [push]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        bin: [peergos, peergos.exe]
        exclude:
          - os: ubuntu-latest
            bin: peergos.exe
          - os: windows-latest
            bin: peergos
          - os: macos-latest
            bin: peergos.exe
    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: Build with Ant
      run: ant -noinput -buildfile build.xml peergos_submodule_sync dist 
    - name: Install GraalVM and native-image
      shell: bash
      run: cd native-build && java InstallNativeImage.java
    - name: Build native image of Peergos
      shell: bash
      run: cd native-build && java BuildNativeImage.java
    - name: Upload Artifact
      uses: actions/upload-artifact@v2
      with:
        name: ${{ matrix.os }}-peergos
        path: "./native-build/${{ matrix.bin }}"