name: Native packager

on: [push]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, ubuntu-24.04-arm, macos-13, macos-latest, windows-latest]
        bin: [peergos, peergos.exe]
        exclude:
          - os: windows-latest
            bin: peergos
          - os: ubuntu-latest
            bin: peergos.exe
          - os: ubuntu-24.04-arm
            bin: peergos.exe
          - os: macos-latest
            bin: peergos.exe
          - os: macos-13
            bin: peergos.exe
      fail-fast: false
    steps:
    - uses: actions/checkout@v4
    - uses: ilammy/msvc-dev-cmd@v1
    - name: Set up JDK
      uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: 23
    - name: Build with Ant
      run: ant -noinput -buildfile build.xml peergos_submodule_sync dist 
    - name: Package for host OS
      shell: bash
      run: cd packager && java PackagePeergos.java
    - name: Extract env var
      if: runner.os == 'Windows'
      run: type artifact | Out-File -FilePath $env:GITHUB_ENV -Append
    - name: Upload package artifact
      uses: actions/upload-artifact@v4
      with:
        name: ${{ env.artifact }}
        path: "./packager/${{ env.artifact }}"
    
