#!/usr/bin/env sh

echo "Installing Peergos"

TARGET_DIR="/usr/local/bin"

if [ ! -d $TARGET_DIR ]
then
    mkdir -p $TARGET_DIR
fi

if [ ! -d $TARGET_DIR ]
then
    TARGET_DIR="/usr/bin"
fi

ln -Ffs "$2/Peergos.app/Contents/MacOS/peergos" "$TARGET_DIR/peergos"

exit 0